### ISSUE TITLE
Some configs use bl_pin: instead of  backlight_pin:

### ISSUE THREAD

**Issue by Teslafly** [pulimento/TTGO-T-Display-esphome-homeassistant-sample#1]
The st7789v driver has been merged into esphome master. 

The backlight pin seems to have been renamed from musk95's driver.

change all config files to use  backlight_pin: 4  instead of bl_pin: 4

Also testing all examples would be a good idea.

**Comment by pulimento** [comment]
Hi!
Yeah, saw that.
The code on this repo, as of now, is not meant to be complete. I don't have the intention to keep it up-to date, although pull requests are welcomed.
Code must work, because it uses a fixed version of esphome, and this code on top of that.
Thanks, I'm close this issue now. Feel free to comment
